apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: metallb-operator-webhook-server-service-cert
  creationTimestamp: null
  name: webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    component: webhook-server
status:
  loadBalancer: {}
