# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/metallb-operator.clusterserviceversion.yaml
- bases/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
- bases/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
- ../../config/default
- ../../config/metallb_rbac
- ../../config/samples
- ../../config/scorecard
patchesStrategicMerge:
- disable-cert-rotation.yaml
- ocpvariables.yaml
- controller-webhook-patch.yaml
- webhookservicecainjection_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
