# This patch add annotation to the webhook service config
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: metallb-operator-webhook-server-service-cert
