apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
<<<<<<<< HEAD:bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  name: prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
========
  name: metallb-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-manager-role
subjects:
- kind: ServiceAccount
  name: manager-account
  namespace: metallb-system
>>>>>>>> upstream/main:bundle/manifests/metallb-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
