# permissions for end users to view metallbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-viewer-role
rules:
- apiGroups:
  - metallb.io
  resources:
  - metallbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metallb.io
  resources:
  - metallbs/status
  verbs:
  - get
