# permissions for end users to edit metallbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-editor-role
rules:
- apiGroups:
  - metallb.io
  resources:
  - metallbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metallb.io
  resources:
  - metallbs/status
  verbs:
  - get
