apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-controller
  namespace: '{{.NameSpace}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - '{{.NameSpace}}'
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-speaker
  namespace: '{{.NameSpace}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
  namespaceSelector:
    matchNames:
      - '{{.NameSpace}}'
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
