apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{.NameSpace}}'
  name: config
data:
  config: |
    address-pools:
    - name: {{ .Name }}
      protocol: {{ .Protocol }}
      addresses:

      {{ range $address := .Addresses -}}
      - {{ $address }}
      {{ end -}}

      {{ $auto_assign := .AutoAssign }} {{ if not $auto_assign }}
      auto-assign: {{ $auto_assign }}
      {{ end }}